services:
  - type: static_site
    name: front-pdv
    rootDir: frontend
    buildCommand: yarn install && yarn build
    publishDir: build
  - type: web_service
    name: backend-pdv
    env: node
    rootDir: backend
    buildCommand: yarn install && tsc
    startCommand: node dist/server.js